#!/bin/bash

moonc ./src
./lp-build.sh
source ./lp-config.sh

butler push "$outputDir/$packageName-${version}_win32.zip" tangentfox/asteroid-dodge:win32 --userversion ${version}
butler push "$outputDir/$packageName-${version}_osx.zip" tangentfox/asteroid-dodge:osx --userversion ${version}
butler push "$outputDir/$packageName-${version}_linux.zip" tangentfox/asteroid-dodge:linux --userversion ${version}
